name: 'Node Lint'
description: 'Steps for running an NPM lint script on Node.js'
inputs:
  package-manager:
    description: 'Node.js package manager to use'
    required: true
    default: 'yarn'
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Load cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-lint-modules-v1-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: ${{ inputs.package-manager }} install --pure-lockfile
    - name: Run linter
      run: ${{ inputs.package-manager }} run lint
